"""initial

Revision ID: 583995e5ef13
Revises: 
Create Date: 2022-08-11 00:52:25.177483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583995e5ef13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
